### ISSUE TITLE
Shutdown button

### ISSUE THREAD

**Issue by dsiminiuk** [OpenRepeater/openrepeater#110]
On the standard Pi OS builds you can add dtoverlay=gpio-shutdown to config.txt and shorting GPIO3 to ground will do a sleep on the Pi. Pressing it again will wake it up.
This does not work on the latest img file.
Is there a recommended way to shutdown the repeater without having to access the web ui?

**Comment by Dloranger** [comment]
@dsiminiuk we would defer to your preferred approach such as mentioned above.  Most of the time we just hard pull of the power, the system has been tolerant to this so far despite it being a bad practice.

we are intentionally keeping many such features out of our images to prevent conflicts and undesirable complexity.
