### ISSUE TITLE
move from mysql to sqlite on embedded

### ISSUE THREAD

**Issue by rneese45** [OpenRepeater/OpenRepeater#12]
I would like to look at moving from mysql to sqlite on arm embedded devices . this will enhance performance and extend the life of the emmc/sd devices.

**Comment by mathewpeterson** [comment]
Yes, I agree - I've been working in migrating all the code to silex and will use Doctrine dbal so switching out the db adapter should be painless.

**Comment by alleghenycreative** [comment]
This has been completed.
