### ISSUE TITLE
database.php

### ISSUE THREAD

**Issue by thejwalker** [OpenRepeater/openrepeater#14]
login.php is attempting to include a file located at "/etc/openrepeater/database.php" - where does this file come from as it's appears to be outside of DOCUMENT_ROOT?

Thanks

**Comment by thejwalker** [comment]
It appears that the contents of ./install/sql/database.php has what's required.

**Comment by abcrawford** [comment]
@thejwalker sorry I wasn't able to get back to you sooner as I was out of town. The files on the GitHub need to be installed. This typically gets built into a debian package which handles putting the files into place. Also We have prebuilt SD card image with debian available at the openrepeater.com website.
