### ISSUE TITLE
GUI on mobile Portrait Mode, menu button doesn't work

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/openrepeater#26]
When using the GUI on a mobile device in portrait mode, the menu button does not respond.  Switching the mobile to a landscape mode the menu button works as expected.

build 27-APR-2017

**Comment by abcrawford** [comment]
I have not been able to replicate the behavior described on iOS device. What platform and browser are you using? Is it still an issue in 2018?

**Comment by Dloranger** [comment]
appears fixed in current android
