### ISSUE TITLE
GPIO expander DTBO not included in the config.txt

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/openrepeater#29]
This may be a feature for the wizard to handle, but suggest loading the DTBO by default, then the wizard can detect if the device is loaded or not, and clear the config.txt entry if not detected.

If done in the wizard, a way to reinsert it should be included for optional add-on boards that may come later.

**Comment by abcrawford** [comment]
This is corrected in the latest 2.x.x build script.
