### ISSUE TITLE
Getting Repository Going and Going Open Source

### ISSUE THREAD

**Issue by alleghenycreative** [OpenRepeater/OpenRepeater#3]
@AngelTomas we can continue our discussion here so others joining in the project later can get up to speed quickly. As you can see I've added you as a contributor to the project. Any help you can provide will be greatly appreciate and help to move this project forward. I will post again soon.

**Comment by gavargas22** [comment]
Hey guys, just checking in. What is the status of the project, I was looking over some of the issues, what else is there to do?

**Comment by alleghenycreative** [comment]
@gavargas22,
Thanks for checking in. I have some offline improvements going on right now as time permits. I am working on making some UI improvements and testing some basic hardware, things that will be needed by others to create a basic functioning system. I plan to post that to Github as soon as I get it done. @mathewpeterson  has been working on building a framework for the web app to clean up that code.

Here are some areas that could be of help to me and help to speed the process along:
One of the new UI features I am working on is better ID customization. Part of that includes allowing the user to choose how many WPM and Frequency of the CW ID. These are variables that get passed into the SVXLink config file. On the front end of the UI I want to create a preview feature to allow the user to test the different setting until they find something that suites there needs. I've already started simplifying an HTML/Javascript approach based off of this site:  http://morsecode.scphillips.com/jtranslator.html
If you are interested in refining that let me know. 

We also need to build some scripts which will probably use both PHP and Shell to start and restart the SVXLink server when the settings are change. I assume you are using the PI image that I created? This has a popup that is designed for this, but the backend is not fully developed yet to handle that task.

Let me know if you can help in either of those areas. Thanks.
