### ISSUE TITLE
On mobile, admin button is obscured in chrome

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/openrepeater#33]
Admin button is hidden under address bar in mobile browser

**Comment by Dloranger** [comment]
![screenshot_2017-05-01-06-41-45](https://cloud.githubusercontent.com/assets/10390925/25581011/d5e63cca-2e39-11e7-9969-d3a820304831.png)

**Comment by abcrawford** [comment]
@Dloranger, files were commited to ionosphere branch last night to address this.

**Comment by abcrawford** [comment]
Closing, see above comment. Will be available in 2.x.x release build.
