### ISSUE TITLE
In ports.php Advanced Details is an empty window

### ISSUE THREAD

**Issue by bobruddy** [OpenRepeater/openrepeater#59]
Configuration: Raspberry PI 3, ics-ctrl 2x, 2.1.x install

When clicking on the advanced details button at the bottom of the screen an empty box shows up. See screen recording attached.

[Screen.Recording.2019-02-05.at.10.13.56.PM.zip](https://github.com/OpenRepeater/openrepeater/files/2843306/Screen.Recording.2019-02-05.at.10.13.56.PM.zip)

**Comment by abcrawford** [comment]
Found the fix for this and pushed up changes
