### ISSUE TITLE
Delay on first transmission before first ident

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/openrepeater#67]
seeing an issue where the ptt does not come up immediately of the first ptt sent. it appears this only occurs if no tx has occured yet for any reason.

simple fix is to force a tx at boot time

edit /usr/share/svxlink/events.d/local/Logic.tcl and add the following process, you can customize this if desired

proc startup {} {
  playMsg "Core" "online"
  #send_short_ident
}

without the change, note the timestamps

> Sun Mar 24 12:54:32 2019: ORP_SimplexLogic_Port2: Event handler script successfully loaded.
> Sun Mar 24 12:54:32 2019: Activating link LinkSection
> Sun Mar 24 12:54:**41** 2019: RX_Port1: The squelch is OPEN (3.38038)
> Sun Mar 24 12:54:**43** 2019: TX_Port1: Turning the transmitter ON

with the change

> Sun Mar 24 12:57:17 2019: ORP_SimplexLogic_Port2: Event handler script successfully loaded.
> Sun Mar 24 12:57:17 2019: Activating link LinkSection
> Sun Mar 24 12:57:19 2019: TX_Port1: Turning the transmitter ON
> Sun Mar 24 12:57:19 2019: TX_Port2: Turning the transmitter ON
> Sun Mar 24 12:57:21 2019: TX_Port1: Turning the transmitter OFF
> Sun Mar 24 12:57:21 2019: TX_Port2: Turning the transmitter OFF
> Sun Mar 24 12:57:**30** 2019: RX_Port1: The squelch is OPEN (3.39565)
> Sun Mar 24 12:57:**30** 2019: TX_Port1: Turning the transmitter ON
> Sun Mar 24 12:57:30 2019: TX_Port2: Turning the transmitter ON

**Comment by Dloranger** [comment]
This may be related

https://groups.io/g/svxlink/topic/strange_problem_repeater/78276017

**Comment by abcrawford** [comment]
@Dloranger  If you've tested this works then go ahead and commit. It looks like it should, but I am not currently working in a live setup.
