### ISSUE TITLE
Create module for remote start of a vehicle

### ISSUE THREAD

**Issue by Dloranger** [OpenRepeater/openrepeater#72]
This issue is a reminder to myself that there is some market interest to create a simple module for the pi-repeater products (mostly the 1x) that will allow the system to monitor a vehicle battery status and make an announcement that the battery is low, and that the engine will be started using the remote start if available.

The use case is for hunting parties to be able to install a 1x controller alongside a duplexor and a couple mobile radios in a vehicle who can then park the vehicle at the top of a hill to use it as a repeater for the group to communicate through.  The concern would be potential battery drain from the mobiles being left on over the stay of the trip (perhaps several days to a week) and the party returning to a dead vehicle.

This will likely be a simplified version of the site-status module, but may require more intelligence on the output GPIO side to actually control the remote starter.

**Comment by abcrawford** [comment]
Interesting topic. But would it not be simpler to have an isolated battery and add some solar panels for charging on the dash?
