### ISSUE TITLE
Custom ident is not playing, still only morse

### ISSUE THREAD

**Issue by lukasalex** [OpenRepeater/openrepeater#87]
Hello guys,
I was testing custom identification. I tried mp3, wav, converted wav/mp3 by sox to 16bit16mhz according to manual but still repeater is using morse. 
Is there any trick or it's a bug?
I am using latest version on Raspberry Pi 3B
Thank you

**Comment by abcrawford** [comment]
When you say you are using the latest version, what is the version number? The latest image version is 2.1.2, unless you are using the build script to create a 2.2.0 image which is development code as of this date. 

How are you uploading your sound files? Manually? You shouldn't need to do any SOX conversion on your end. Just upload a WAV or MP3 file via the upload button on the Identification page (when in custom mode) and select the file after uploaded. The upload process will take care of converting the audio in the background to the appropriate sampling rate of WAV file that SVXLink expects. 

You may need to refresh the page when changing modes. Sometimes the AJAX doesn't take. Be sure to rebuild and restart after the changes are made to apply them to the live system. Also be sure to check the Log tab, maybe open up in a separate browser tab. If you have bad audio files that cannot be played, you should see it there. I am suspecting if you converted the file yourself and it cannot play it via SVXLink and you have append morse ID option selected then that might be why you are only hearing the CW. The log should make that clear. Hope that helps.

**Comment by lukasalex** [comment]
Hi Aaron, 
thank you for your inputs. 

I am running 2.1.2 official release, using USB audio dongle, 
![image](https://user-images.githubusercontent.com/76724565/103466625-e9c54080-4d46-11eb-9248-7dab236796d5.png)
Here is my config for identification:
![image](https://user-images.githubusercontent.com/76724565/103466662-2133ed00-4d47-11eb-8515-1a00f311c38e.png)
After this I am restarting the service by red notification and checking logs, but as you said, somwhere will be mistake, it's not sending log about identification service, only sending log about morse long/short but it's 4 seconds long (mp3/wav is 7 seconds).
![image](https://user-images.githubusercontent.com/76724565/103466651-10837700-4d47-11eb-8e5c-8e28f8d08efc.png)
Here are sounds, before and after upload.
[sounds.zip](https://github.com/OpenRepeater/openrepeater/files/5760872/sounds.zip)

Thank you for any advice ;-)
Lukas

**Comment by lukasalex** [comment]
Hi. I tried to upload again samples and set it as identification file, changed time so short is 1 minute, long is 10 minutes and still it's using morse.
![CBD877C3-54C9-4293-BA5E-9F21BC95ECF4](https://user-images.githubusercontent.com/76724565/103471268-88b95f00-4d7e-11eb-9061-4e011ab896b7.png)

![CA3B9FBF-0FDA-4509-B782-9497BD6A5E5C](https://user-images.githubusercontent.com/76724565/103471274-8e16a980-4d7e-11eb-8baa-ec22425de221.png)

![F659B293-58D9-49D3-97D7-BADDE0E3910A](https://user-images.githubusercontent.com/76724565/103471270-8b1bb900-4d7e-11eb-8ffb-2366e2f94057.png)
![1B5A333D-BFF4-42CE-A2DE-5555EC6B0232](https://user-images.githubusercontent.com/76724565/103471272-8c4ce600-4d7e-11eb-8f5e-8ac9e4cfe02f.png)
![57E969F5-06D1-4956-905C-B6F23640C5F0](https://user-images.githubusercontent.com/76724565/103471273-8ce57c80-4d7e-11eb-8b7b-a3bcd7c402ce.png)

**Comment by lukasalex** [comment]
And here is backup file [jn89fc_2021-01-03_05-28-42.zip](https://github.com/OpenRepeater/openrepeater/files/5761211/jn89fc_2021-01-03_05-28-42.zip)

**Comment by lukasalex** [comment]
Ahaaa, I find it: 
/usr/share/svxlink/events.d/local/Logic.tcl
here is 
if {$CFG_TYPE == "Repeater"} - I am running Simplex

so I changed it to if {"x"=="x"} and now it's sending wav file to TX :)
So if you can add Identification for Simplex too (or... I should let it with "x" ? 👍 

But after change it's back, so I need to find, where it is build. But it's going good way :-)

Lukas

**Comment by lukasalex** [comment]
/var/www/openrepeater/includes/classes# vi ./SVXLink_TCL.php

Edited so now it's still active :-)

Lukas

**Comment by abcrawford** [comment]
@lukasalex, Sorry for the delay. I was waiting until I had the opportunity to try and download your sound files and test for myself. I didn't notice your additional comments because of how my email grouped the replies. 

Glad to hear that you got it figured. out. I didn't know that you were running it in simplex mode. Yes as you discovered the CW ID is/was hard coded. The simplex node option was originally created as a work around to allow for simplex echolink node usage and I guess it was thought at the time that nothing more would be needed than CW. That part of the UI is in the process of being reworked so that should change in a future release.

**Comment by lukasalex** [comment]
Thank you for your reply ;-) 

I have one additional question, so I will open it in new case ;-) 

Lukas
